Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -55,7 +55,7 @@ jobs:
           DOCKER_EMAIL: ${{ secrets.DOCKER_EMAIL }}
         run: |
           kubectl create secret docker-registry image-registry-secret \
-            --docker-server=192.168.1.36:5000 \
+            --docker-server=192.168.1.37:5000 \
             --docker-username=$DOCKER_USERNAME \
             --docker-password=$DOCKER_PASSWORD \
             --docker-email=$DOCKER_EMAIL \
@@ -68,12 +68,13 @@ jobs:
             -n $NAMESPACE \
             -p '{"imagePullSecrets":[{"name":"image-registry-secret"}]}' || true
 
-      - name: Debug - Confirm values.yaml exists
-        run: ls -l $VALUES_FILE
+      - name: Debug path
+        run: |
+          echo "Looking for file: $VALUES_FILE"
+          ls -l tomcat-sampleapp/config/stg/values.yaml || echo "Missing"
 
       - name: Deploy using Helm
-        working-directory: ${{ github.workspace }}
         run: |
           helm upgrade --install $RELEASE_NAME ./helm-chart \
             -n $NAMESPACE \
-            -f $VALUES_FILE
+            -f tomcat-sampleapp/config/stg/values.yaml
