Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -14,12 +14,15 @@ jobs:
     steps:
       - name: Checkout App Code
         uses: actions/checkout@v3
+        with:
+          path: tomcat-sampleapp
 
       - name: Login to Nexus Docker Registry
         run: echo "${{ secrets.NEXUS_PASSWORD }}" | docker login 192.168.1.37:5000 -u ${{ secrets.NEXUS_USERNAME }} --password-stdin
 
       - name: Build Docker Image
-        run: docker build -t $IMAGE_NAME:latest ./tomcat-sampleapp
+        working-directory: tomcat-sampleapp
+        run: docker build -t $IMAGE_NAME:latest .
 
       - name: Push Docker Image
         run: docker push $IMAGE_NAME:latest
@@ -65,13 +68,13 @@ jobs:
             -n $NAMESPACE \
             -p '{"imagePullSecrets":[{"name":"image-registry-secret"}]}' || true
 
-      - name: Debug path
+      - name: Confirm values.yaml exists
         run: |
           echo "Looking for file: $VALUES_FILE"
-          ls -l $VALUES_FILE || echo "Missing"
+          ls -l tomcat-sampleapp/config/stg/values.yaml || (echo "Missing values.yaml!" && exit 1)
 
       - name: Deploy using Helm
         run: |
           helm upgrade --install $RELEASE_NAME ./helm-chart \
             -n $NAMESPACE \
-            -f $VALUES_FILE
+            -f tomcat-sampleapp/config/stg/values.yaml
