Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -14,13 +14,12 @@ jobs:
     steps:
       - name: Checkout App Code
         uses: actions/checkout@v3
-  
+
       - name: Login to Nexus Docker Registry
         run: echo "${{ secrets.NEXUS_PASSWORD }}" | docker login 192.168.1.37:5000 -u ${{ secrets.NEXUS_USERNAME }} --password-stdin
 
       - name: Build Docker Image
-        working-directory: tomcat-sampleapp
-        run: docker build -t $IMAGE_NAME:latest .
+        run: docker build -t $IMAGE_NAME:latest ./tomcat-sampleapp
 
       - name: Push Docker Image
         run: docker push $IMAGE_NAME:latest
@@ -69,7 +68,7 @@ jobs:
       - name: Debug path
         run: |
           echo "Looking for file: $VALUES_FILE"
-          ls -l tomcat-sampleapp/config/stg/values.yaml || echo "Missing"
+          ls -l $VALUES_FILE || echo "Missing"
 
       - name: Deploy using Helm
         run: |
